// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductCatalog.Api.Infrastructure;

#nullable disable

namespace ProductCatalog.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductCatalog.Api.Domain.Entities.Bodega", b =>
                {
                    b.Property<int>("BodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bod_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BodId"));

                    b.Property<string>("BodNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bod_nombre");

                    b.Property<bool>("BodPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bod_principal");

                    b.HasKey("BodId");

                    b.ToTable("bodegas", (string)null);
                });

            modelBuilder.Entity("ProductCatalog.Api.Domain.Entities.Inventario", b =>
                {
                    b.Property<int>("ProdId")
                        .HasColumnType("integer")
                        .HasColumnName("prod_id");

                    b.Property<int>("BodId")
                        .HasColumnType("integer")
                        .HasColumnName("bod_id");

                    b.Property<DateTime>("InvLastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inv_last_update");

                    b.Property<int>("InvStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("inv_stock");

                    b.HasKey("ProdId", "BodId");

                    b.HasIndex("BodId");

                    b.ToTable("inventario", (string)null);
                });

            modelBuilder.Entity("ProductCatalog.Api.Domain.Entities.Movimiento", b =>
                {
                    b.Property<int>("MovId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mov_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovId"));

                    b.Property<int?>("MovBodegaFinal")
                        .HasColumnType("integer")
                        .HasColumnName("mov_bodega_final");

                    b.Property<int?>("MovBodegaInicial")
                        .HasColumnType("integer")
                        .HasColumnName("mov_bodega_inicial");

                    b.Property<int>("MovCantidad")
                        .HasColumnType("integer")
                        .HasColumnName("mov_cantidad");

                    b.Property<string>("MovConcepto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mov_concepto");

                    b.Property<DateTime>("MovFecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mov_fecha");

                    b.Property<string>("MovTipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mov_tipo");

                    b.Property<int>("ProdId")
                        .HasColumnType("integer")
                        .HasColumnName("prod_id");

                    b.HasKey("MovId");

                    b.HasIndex("ProdId");

                    b.ToTable("movimientos", (string)null);
                });

            modelBuilder.Entity("ProductCatalog.Api.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prod_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProdId"));

                    b.Property<string>("ProdCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prod_codigo");

                    b.Property<string>("ProdDescripcion")
                        .HasColumnType("text")
                        .HasColumnName("prod_descripcion");

                    b.Property<string>("ProdMarca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prod_marca");

                    b.Property<string>("ProdNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("prod_nombre");

                    b.HasKey("ProdId");

                    b.HasIndex("ProdCodigo")
                        .IsUnique();

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("ProductCatalog.Api.Domain.Entities.Inventario", b =>
                {
                    b.HasOne("ProductCatalog.Api.Domain.Entities.Bodega", "Bodega")
                        .WithMany()
                        .HasForeignKey("BodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductCatalog.Api.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProductCatalog.Api.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("ProductCatalog.Api.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
